[2025-01-30T23:43:00.530+0000] {processor.py:186} INFO - Started process (PID=481) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:00.535+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:43:00.595+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:00.552+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:00.836+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:00.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 7, in <module>
    from hooks.openweaterhook import OpenWeatherHook
ModuleNotFoundError: No module named 'hooks.openweaterhook'
[2025-01-30T23:43:00.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:01.324+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 1.004 seconds
[2025-01-30T23:43:06.456+0000] {processor.py:186} INFO - Started process (PID=486) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:06.461+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:43:06.464+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:06.464+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:06.473+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:06.471+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 7, in <module>
    from hooks.openweaterhook import OpenWeatherHook
ModuleNotFoundError: No module named 'hooks.openweaterhook'
[2025-01-30T23:43:06.474+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:06.535+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.102 seconds
[2025-01-30T23:43:11.616+0000] {processor.py:186} INFO - Started process (PID=491) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:11.637+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:43:11.639+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:11.639+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:11.644+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:11.643+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 7, in <module>
    from hooks.openweaterhook import OpenWeatherHook
ModuleNotFoundError: No module named 'hooks.openweaterhook'
[2025-01-30T23:43:11.645+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:11.707+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.099 seconds
[2025-01-30T23:43:16.805+0000] {processor.py:186} INFO - Started process (PID=496) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:16.806+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:43:16.809+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:16.809+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:16.815+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:16.814+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 7, in <module>
    from hooks.openweaterhook import OpenWeatherHook
ModuleNotFoundError: No module named 'hooks.openweaterhook'
[2025-01-30T23:43:16.816+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:16.938+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.143 seconds
[2025-01-30T23:43:22.033+0000] {processor.py:186} INFO - Started process (PID=501) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:22.062+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:43:22.066+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:22.065+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:22.076+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:22.072+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 7, in <module>
    from hooks.openweaterhook import OpenWeatherHook
ImportError: cannot import name 'OpenWeatherHook' from 'hooks.openweaterhook' (/opt/airflow/dags/hooks/openweaterhook.py). Did you mean: 'openweaterhook'?
[2025-01-30T23:43:22.078+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:22.128+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.104 seconds
[2025-01-30T23:43:27.203+0000] {processor.py:186} INFO - Started process (PID=512) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:27.229+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:43:27.232+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:27.232+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:27.239+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:27.237+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 7, in <module>
    from hooks.openweaterhook import OpenWeatherHook
ImportError: cannot import name 'OpenWeatherHook' from 'hooks.openweaterhook' (/opt/airflow/dags/hooks/openweaterhook.py). Did you mean: 'openweaterhook'?
[2025-01-30T23:43:27.241+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:27.308+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.111 seconds
[2025-01-30T23:43:32.387+0000] {processor.py:186} INFO - Started process (PID=517) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:32.388+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:43:32.391+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:32.390+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:33.865+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:33.863+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:43:33.866+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:33.921+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 1.541 seconds
[2025-01-30T23:43:39.022+0000] {processor.py:186} INFO - Started process (PID=522) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:39.050+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:43:39.052+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:39.052+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:39.071+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:39.070+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:43:39.071+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:39.110+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.099 seconds
[2025-01-30T23:43:44.172+0000] {processor.py:186} INFO - Started process (PID=527) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:44.174+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:43:44.178+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:44.177+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:44.196+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:44.195+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:43:44.196+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:44.239+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.074 seconds
[2025-01-30T23:43:49.341+0000] {processor.py:186} INFO - Started process (PID=532) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:49.390+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:43:49.399+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:49.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:49.447+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:49.445+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:43:49.448+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:49.495+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.177 seconds
[2025-01-30T23:43:54.558+0000] {processor.py:186} INFO - Started process (PID=537) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:54.565+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:43:54.567+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:54.567+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:54.584+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:54.582+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:43:54.584+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:54.623+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.072 seconds
[2025-01-30T23:43:59.711+0000] {processor.py:186} INFO - Started process (PID=548) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:59.711+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:43:59.714+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:59.714+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:59.734+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:43:59.732+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:43:59.735+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:43:59.826+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.124 seconds
[2025-01-30T23:44:04.917+0000] {processor.py:186} INFO - Started process (PID=553) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:04.918+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:44:04.921+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:04.921+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:04.936+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:04.935+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:44:04.936+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:05.010+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.106 seconds
[2025-01-30T23:44:10.054+0000] {processor.py:186} INFO - Started process (PID=558) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:10.054+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:44:10.056+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:10.056+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:10.071+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:10.070+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:44:10.071+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:10.148+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.100 seconds
[2025-01-30T23:44:15.283+0000] {processor.py:186} INFO - Started process (PID=563) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:15.311+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:44:15.317+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:15.316+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:15.351+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:15.350+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:44:15.352+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:15.396+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.132 seconds
[2025-01-30T23:44:20.527+0000] {processor.py:186} INFO - Started process (PID=568) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:20.528+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:44:20.533+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:20.532+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:20.552+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:20.551+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:44:20.553+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:20.592+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.086 seconds
[2025-01-30T23:44:25.696+0000] {processor.py:186} INFO - Started process (PID=579) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:25.720+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:44:25.722+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:25.722+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:25.741+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:25.740+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:44:25.741+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:25.785+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.105 seconds
[2025-01-30T23:44:30.903+0000] {processor.py:186} INFO - Started process (PID=584) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:30.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:44:30.929+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:30.928+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:30.956+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:30.955+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:44:30.956+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:31.016+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.125 seconds
[2025-01-30T23:44:36.096+0000] {processor.py:186} INFO - Started process (PID=589) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:36.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:44:36.101+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:36.100+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:36.119+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:36.118+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:44:36.120+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:36.158+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.072 seconds
[2025-01-30T23:44:41.253+0000] {processor.py:186} INFO - Started process (PID=594) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:41.254+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:44:41.259+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:41.258+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:41.280+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:41.279+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:44:41.281+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:41.329+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.089 seconds
[2025-01-30T23:44:46.404+0000] {processor.py:186} INFO - Started process (PID=599) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:46.497+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:44:46.503+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:46.502+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:46.526+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:46.525+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:44:46.527+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:46.616+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.220 seconds
[2025-01-30T23:44:51.747+0000] {processor.py:186} INFO - Started process (PID=604) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:51.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:44:51.759+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:51.758+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:51.778+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:51.777+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:44:51.779+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:51.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.089 seconds
[2025-01-30T23:44:56.913+0000] {processor.py:186} INFO - Started process (PID=615) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:56.914+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:44:56.917+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:56.916+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:56.934+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:44:56.933+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:44:56.934+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:44:56.980+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.080 seconds
[2025-01-30T23:45:02.035+0000] {processor.py:186} INFO - Started process (PID=620) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:02.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:45:02.037+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:45:02.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:02.053+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:45:02.052+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:45:02.054+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:02.092+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.063 seconds
[2025-01-30T23:45:07.193+0000] {processor.py:186} INFO - Started process (PID=625) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:07.194+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:45:07.198+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:45:07.197+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:07.218+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:45:07.217+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:45:07.219+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:07.270+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.089 seconds
[2025-01-30T23:45:12.374+0000] {processor.py:186} INFO - Started process (PID=630) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:12.375+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:45:12.378+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:45:12.378+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:12.397+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:45:12.396+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:45:12.398+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:12.438+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.080 seconds
[2025-01-30T23:45:17.536+0000] {processor.py:186} INFO - Started process (PID=635) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:17.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:45:17.542+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:45:17.541+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:17.560+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:45:17.559+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:45:17.561+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:17.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.085 seconds
[2025-01-30T23:45:22.704+0000] {processor.py:186} INFO - Started process (PID=640) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:22.705+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:45:22.709+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:45:22.708+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:22.729+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:45:22.728+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:45:22.729+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:22.774+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.087 seconds
[2025-01-30T23:45:27.868+0000] {processor.py:186} INFO - Started process (PID=651) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:27.870+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:45:27.874+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:45:27.873+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:27.893+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:45:27.891+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:45:27.893+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:28.030+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.181 seconds
[2025-01-30T23:45:33.154+0000] {processor.py:186} INFO - Started process (PID=656) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:33.229+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:45:33.233+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:45:33.233+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:33.256+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:45:33.254+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:45:33.256+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:33.356+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.219 seconds
[2025-01-30T23:45:38.439+0000] {processor.py:186} INFO - Started process (PID=661) to work on /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:38.472+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/operators/tempoagoraoperator.py for tasks to queue
[2025-01-30T23:45:38.475+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:45:38.474+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:38.497+0000] {logging_mixin.py:190} INFO - [2025-01-30T23:45:38.495+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/operators/tempoagoraoperator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/operators/tempoagoraoperator.py", line 8, in <module>
    from operators.openweatheroperator import OpenWeatherOperator
  File "/opt/airflow/dags/operators/openweatheroperator.py", line 4, in <module>
    from src.dados.iinfra_dados import IinfraDados
ModuleNotFoundError: No module named 'src'
[2025-01-30T23:45:38.497+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/operators/tempoagoraoperator.py
[2025-01-30T23:45:38.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/operators/tempoagoraoperator.py took 0.108 seconds
